# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.creds_DOCKER_USERNAME }}
        password: ${{ secrets.creds_DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.creds_DOCKER_USERNAME }}/node-k8s-app:latest .
        docker push ${{ secrets.creds_DOCKER_USERNAME }}/node-k8s-app:latest
