name: Build and Deploy Node.js App to AKS

on:
  push:
    branches:
      - develop

env:
  RESOURCE_GROUP: nodejs-rg
  CLUSTER_NAME: nodejs-aks
  ACR_NAME: nodejsacr123

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6 # Specify your desired version

    - name: Terraform Init
      working-directory: infra
      run: terraform init

    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve

    - name: Set AKS context
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

    - name: Build & Push Docker Image
      run: |
        az acr login --name $ACR_NAME
        docker build -t $ACR_NAME.azurecr.io/nodejs-app:latest .
        docker push $ACR_NAME.azurecr.io/nodejs-app:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
